### ISSUE TITLE
Sample website on latest commit does not work

### ISSUE THREAD

**Issue by jclifford** [troygoode/MembershipStarterKit#1]
Using TroyGoode-MembershipStarterKit-6620fde.zip,

Bug:
The sample website generates no URL for Html.ActionLink("User Administration", "Index", "UserAdministration", new { Area = "UserAdministration" }, new { }) in Site.Master

Fix:
The AreaName at line 12 in UserAdministrationAreaRegistration.cs should be "UserAdministration" not "MvcMembership"

HTH

**Comment by troygoode** [comment]
Thanks, this has been fixed.
