### ISSUE TITLE
Support SimpleMembership

### ISSUE THREAD

**Issue by ardalis** [troygoode/MembershipStarterKit#17]
SimpleMembership is another membership provider that ships with WebMatrix but can also be used on its own.  More on it here:
http://blog.osbornm.com/archive/2010/07/21/using-simplemembership-with-asp.net-webpages.aspx

Apparently it doesn't support the FindAll() method, so the MvcMembership.UserAdministrationController.Index() method blows up here:
Users = _userService.FindAll(page ?? 0, PageSize),

Seeking a workaround or update to the codebase, thanks!

**Comment by troygoode** [comment]
Hey ardalis - just wanted to follow up on this. Is there a reason you closed this issue right after opening it? Should I assume that I don't need to investigate this further?

**Comment by ardalis** [comment]
I switched back to aspnet standard membership provider, so I don't need
it, but others still might. The real challenge is that simple
membership doesn't implement most of the API.

Sent from my Windows Phone From: Troy Goode
Sent: Saturday, September 24, 2011 9:57 AM
To: ardalis
Subject: Re: [MembershipStarterKit] Support SimpleMembership (#17)
Hey ardalis - just wanted to follow up on this. Is there a reason you
closed this issue right after opening it? Should I assume that I don't
need to investigate this further?

##
