### ISSUE TITLE
Nuget package brings in a lot of stuff...

### ISSUE THREAD

**Issue by brgrz** [troygoode/MembershipStarterKit#18]
...is there a way for you to create a Nuget package that would only contain code, basically only the assembly without the stuff in Area and Views? I know this has a lot to do with how Nuget packager works but I was just wondering because I essentially only use your classes but have my own controller, views, membership provider etc..

**Comment by troygoode** [comment]
The "MvcMembership" package is code only. "MvcMembership.Mvc" (which relies on the other package) contains the areas, CSS, etc.

**Comment by brgrz** [comment]
thank you
