### ISSUE TITLE
Doesn't work with T4MVC

### ISSUE THREAD

**Issue by carlhoerberg** [troygoode/MembershipStarterKit#2]
T4MVC (http://mvccontrib.codeplex.com/wikipage?title=T4MVC) will find a View folder without a corresponding Controller and therefor fail.

**Comment by jclifford** [comment]
I am successfully using T4MVC with the kit. I do not recall any issues with T4MVC.

**Comment by carlhoerberg** [comment]
the current trunk has the controller in the assembly, unlike the code which you can see at codeplex..

**Comment by troygoode** [comment]
The newest source has the controller back in the website's area, so it should work fine with T4MVC. I don't use it though, so let me know if I'm wrong...
