### ISSUE TITLE
How to implement User Profiles

### ISSUE THREAD

**Issue by cpherjennings** [troygoode/MembershipStarterKit#21]
I've used an older version of the start kit for a while and I'm currently upgrading to the newest version. However, I noticed that there's no implementation for User Profiles. Did I miss something? I can try to implement them on my own, but do you have any suggestions about how to do this while keeping with your current architecture? I think I have a class called WebProfile, which looks like it was generated from something else.
-Chris

**Comment by troygoode** [comment]
Profiles can be implemented using Microsoft's Profile Provider system:

http://odetocode.com/articles/440.aspx

Just add the fields you need to the CreateUser.cshtml & Details.cshtml views, and add code to the UserAdministrationController.cs's CreateUser & Details routes to save the data.
