### ISSUE TITLE
"Email" - Type or namespace expected

### ISSUE THREAD

**Issue by krokonoster** [troygoode/MembershipStarterKit#22]
In CreateUserViewModel
ln.20:
    [Required, Email]

Changed to (only in my copy):
   [Required, DataType(DataType.EmailAddress)]

Not sure this is what was supposed to be there?

**Comment by troygoode** [comment]
The "Email" data annotation is defined in the DataAnnotationsExtensions nuget package (https://github.com/srkirkland/DataAnnotationsExtensions). Make sure you have that and the DataAnnotationsExtensions.MVC3 packages installed.
