### ISSUE TITLE
The type 'PagedList.IPagedList`1<T0>' is defined in an assembly that is not referenced.

### ISSUE THREAD

**Issue by krokonoster** [troygoode/MembershipStarterKit#23]
I added the "MVCMembership" as well as "PagedList" projects to my solution (wanted the source code, so I can have a look at your code to understand it)

However, when building I get this error I can't make go away:
Error   84  The type 'PagedList.IPagedList`1<T0>' is defined in an assembly that is not referenced. You must add a reference to assembly 'PagedList, Version=1.10.0.0, Culture=neutral, PublicKeyToken=abbb863e9397c5e1'.   D:\Dropbox\Source Code\1 - Own Projects\profusion\src\profusion.web\Areas\MvcMembership\Controllers\UserAdministrationController.cs 51  4   profusion.web

Any idea?

I most definitely have a reference from my web project (mvc3) to the MVCMembership project. (Thanks R#  :-) )

**Comment by troygoode** [comment]
I probably have to update MvcMembership to use the latest rev of PagedList. Will try to do so tonight...

**Comment by krokonoster** [comment]
That did it.  I removed the PagedList ref in MvcMembership, and referenced the PagedList project.
Problem solved.  Thanks!
ps:  I'm new to github so rather not try do things like pushing changes to others projects.

**Comment by krokonoster** [comment]
I spoke to fast.  There are some other problems due to PagedList's source code are not up to date (such as there is no Html.PagedListPager in there).
Perhaps when you got time you can update it for us.  This is really good stuff, btw!

**Comment by troygoode** [comment]
> such as there is no Html.PagedListPager in there

Hmmm, I'm guessing you didn't also reference PagedList.Mvc then?

**Comment by krokonoster** [comment]
You are right.  Was going to this evening, but then saw you updated both PagedList and the MembershipStarterKit.  So just updated it on my side and all works.  Thanks a mill!
