### ISSUE TITLE
System.Security.SecurityException: That assembly does not allow partially trusted callers

### ISSUE THREAD

**Issue by NoseBagUK** [troygoode/MembershipStarterKit#3]
Hi,

I am getting the above error when I install to my shared hosting provider.

I found a post where you said that it had been fixed, but I have downloaded the latest version from here and am getting the same error message.

Any ideas?

Thanks in advance

Phil

**Comment by troygoode** [comment]
This should now be fixed in the latest source. Please open a new issue if it isn't!
