### ISSUE TITLE
New Feature: add "Forgot Password" form

### ISSUE THREAD

**Issue by troygoode** [troygoode/MembershipStarterKit#4]
Suggested by promaxcoq and justabuzz on CodePlex.
## promaxcoq (Apr 16 2010) at 2:25 AM

> I did not find any example for reset password for the users not administrator. I am not familiar with MVC. I mean users forgot their password and they want to reset which is known user-name or valid e-mails.
## justabuzz (June 24 2010) at 7:51 AM

> Hi Troy, I think that what promaxcog was trying to say is that if I cannot login because I forgot my password then there's no API for resetting your password (that's usernmae -> secret question / answer flow). The supplied ChangePassword action is designed for logged on users who want to change their passwords. Did you add something for Forgot Password scenario? Thanks!

**Comment by fschwiet** [comment]
justabuzz, its not obvious but that can be done.  Use IUserService.Find*() to get a MembershipUser.  Then call MembershipUser user.ResetPassword(), storing the password given to you.  As that is the new current password, you can then call user.ChangePassword(currentPassword, newPassword).

**Comment by troygoode** [comment]
I've now added a wrapper method for ChangePassword(currentPassword,newPassword) as well ChangePassword(newPassword) - which uses the technique described above by rfschwiet - to the MvcMembership membership facade library. This should enable anyone to easily create their own Forgot Password page now.

I've considered adding a Forgot Password page to the starter kit itself, but one of the things I like to have my Forgot Password pages do is send out an email with a link the user must click. When the user clicks the link it causes the actual password change to take place. This requires some sort of persistence beyond what the Membership API allows, and I don't want to start having the Membership Starter Kit include DB access - this project is intended to work across technologies (NH, EF, L2SQL, Mongo, etc).

**Comment by fschwiet** [comment]
ditto, thats why I had this response.  :)  I was thinking a bit about this code more, Ayende has a blog post where he calls out AccountController as being particularly bad.

Maybe it we could have an IRepository the user must implement.  For a reference implementation, just store the password reset keys in memory or something.

What did you use to render the email?  For sharing this feature I thought it might be better to wait for MVC 3 + Razor view engine, which potentially runs outside of the MVC pipeline.

**Comment by troygoode** [comment]
I actually always use Spark as my view engine (I only use WebForms view engine for this project because of the wider usage) and it is quite easy to use for templating HTML emails as well. I should do a blog post on that... I'll definitely be upgrading the starter kit to use MVC3 + Razor, perhaps even quite soon.

An in-memory implementation (using a singleton or something) isn't a bad idea. You've got my gears grinding now. :-)

**Comment by patrick-robin** [comment]
Why not make use of the security question/answer to provide users with the ability to change their password if they've forgotten it?

**Comment by fschwiet** [comment]
Those kind of security questions are insecure.  Usually the questions are not too hard for someone else to answer.

**Comment by patrick-robin** [comment]
I agree, but it is part of the membership provider model, it would be good to see it implemented here and then it's up to the user whether they utilise it or not.

**Comment by drewid** [comment]
Hmm...  I agree that the functionality for a user to reset their own password (and I used to have to do it ALL the time with sites until I started using RoboForm) is very essential in a membership scenario.  I also like/prefer the send an email to the email address on file and click to walk through changing the password.

Anybody have any progress on this issue in the past few months?

**Comment by JaySmith-zz** [comment]
I have started using this  on several project and am insterested in getting involved with the project and am also interested in try to solve this issue.

**Comment by troygoode** [comment]
The more I think about it the more this doesn't belong in this project. The rest of this project is "administrative" whereas a forgotten password is user-facing - this would make more sense as a separate nuget package (and thus a different project).

**Comment by JaySmith-zz** [comment]
Now that I think about it that does make more sense.

Jay Smith 

Sent from my Windows Phone 7!

-----Original Message-----
