### ISSUE TITLE
New functionality: Add to NuGet

### ISSUE THREAD

**Issue by danmiser** [troygoode/MembershipStarterKit#7]
I see you added NuGet functionality to PagedList. It would be nice to have this in NuGet, too.

**Comment by troygoode** [comment]
I added two packages to NuGet: MvcMembership (the core library) and MvcMembership.Mvc (the area with controllers, views, etc).

**Comment by Thieum** [comment]
you should add tags to make them easily findable, for exemple "membership".

**Comment by troygoode** [comment]
tags have been added to the latest nuget release (3.1)
