### ISSUE TITLE
Add "Create User" functionality

### ISSUE THREAD

**Issue by danmiser** [troygoode/MembershipStarterKit#8]
Right now, we can:
1. Create the user via AccountController/Register. This doesn't allow for initial assignment of roles.
1. Use the ASP.NET Configuration page, which is a developer-focused tool vs. an end-user tool.

It would be nice to allow for creation of users, with an initial assignment of roles that you also choose.

**Comment by troygoode** [comment]
This is now in.

**Comment by danmiser** [comment]
I appreciate that it made it in, but 2 things are missing:
1. A confirm password textbox to ensure that the password gets entered correctly
2. The ability to assign an initial role (or roles)

**Comment by troygoode** [comment]
rather than reopen this issue I have logged a new issue for those (good) suggestions here:

https://github.com/TroyGoode/MembershipStarterKit/issues/14
