### ISSUE TITLE
MVC3 & Razor

### ISSUE THREAD

**Issue by rtrm** [troygoode/MembershipStarterKit#9]
Would be very useful to have a MVC3 / Razor version.

**Comment by beechtreetech** [comment]
I sent Troy a patch for Razor a while back. Here are the contents if you want to add them to your fork: http://dl.dropbox.com/u/396448/RazorViewsForMemStarterKit.rar

**Comment by rtrm** [comment]
Thanks very much, works a charm.

Only issue I had was that View.Title needed changing to ViewBag.Title.

**Comment by troygoode** [comment]
Switched to MVC3 + Razor (CSHTML).
